from .api_views import SummaryRequestViewSet
from .api_views import FileUploadViewSet
from .auth_views import login_view
from .auth_views import logout_view
from .auth_views import register_view
from .web_views import home_view
from .web_views import history_view
from .web_views import files_view
from .web_views import request_detail_view
